### PR TITLE
Fix `setR`

### LINKED ISSUE #16: `setR` reverses its argument
`setR` reverses its argument. For example, `setR [4, 5, 6] [ 1 * 2 * 3 ] == [ 1 * 2 * 6 5 4 ]`. 

Would you like me to submit a fix?

Attached: a property test suite that helped me diagnose the issue

```
module Tests.Pivot exposing (pivotTests)

import Expect
import Fuzz exposing (Fuzzer)
import Pivot exposing (Pivot)
import Test exposing (Test, describe)


genPivotInt : Fuzzer (Pivot Int)
genPivotInt =
    Fuzz.map3
        (\a b c -> Pivot.singleton b |> Pivot.setL a |> Pivot.setR c)
        (Fuzz.list Fuzz.int)
        Fuzz.int
        (Fuzz.list Fuzz.int)


genListInt : Fuzzer (List Int)
genListInt =
    Fuzz.list Fuzz.int


pivotTests : Test
pivotTests =
    describe "pivot"
        [ Test.fuzz genPivotInt "setL (getL a) == a" <|
            \pivot ->
                Pivot.setL (Pivot.getL pivot) pivot
                    |> Expect.equal pivot
        , Test.fuzz2 genListInt genPivotInt "getL (setL l a) == l" <|
            \list pivot ->
                Pivot.getL (Pivot.setL list pivot)
                    |> Expect.equal list
        , Test.fuzz genPivotInt "setR (getR a) == a" <|
            \pivot ->
                Pivot.setR (Pivot.getR pivot) pivot
                    |> Expect.equal pivot
        , Test.fuzz2 genListInt genPivotInt "getR (setR l a) == l" <|
            \list pivot ->
                Pivot.getR (Pivot.setR list pivot)
                    |> Expect.equal list
        , Test.fuzz3 Fuzz.int genListInt genPivotInt "goR (setR (x :: xs) a) == Just (setR xs (appendGoR x a))" <|
            \x xs pivot ->
                Pivot.goR (Pivot.setR (x :: xs) pivot)
                    |> Expect.equal (Just (Pivot.setR xs (Pivot.appendGoR x pivot)))

        ]
```

### PR DESCRIPTION
**Pull request by LightAndLight**
Closes #16

### CODE REVIEW

File: src/Pivot/Modify.elm [hunk 1]
```diff
@@ -12,14 +12,28 @@ setC c_ (Pivot c ( l, r )) =
     Pivot c_ ( l, r )
 
 
+{-|
+
+    setL [ 1, 2, 3 ] [ 99 * 4 * 5 ] == [ 1 2 3 * 4 * 5 ]
+
+    getL >> setL == identity
+
+-}
```
Comment (yotamDvir) [inline src/Pivot/Modify.elm:21]: Documentation should appear in the main `Pivot.elm` file.

File: src/Pivot/Modify.elm [hunk 2]
```diff
@@ -12,14 +12,28 @@ setC c_ (Pivot c ( l, r )) =
...
     Pivot c ( List.reverse l_, r )
 
 
+{-|
+
+    setR [ 3, 4, 5 ] [ 1 * 2 * 99 ] == [ 1 * 2 * 3 4 5 ]
+
+    getR >> setR == identity
+
+-}
```
Comment (yotamDvir) [inline src/Pivot/Modify.elm:33]: Documentation should appear in the main `Pivot.elm` file.

**Review by yotamDvir — CHANGES_REQUESTED** [review]
Thanks, look good. After you move the documentation I'll merge.

**Comment by LightAndLight** [comment]
Updated
